"""empty message

Revision ID: 063b4e20b505
Revises: 
Create Date: 2023-09-13 00:41:29.683626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063b4e20b505'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_rut'), 'users', ['rut'], unique=True)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('breed', sa.String(length=64), nullable=False),
    sa.Column('chip', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attentions_benefits',
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.Column('attention_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attention_id'], ['attentions.id'], ),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefits.id'], ),
    sa.PrimaryKeyConstraint('benefit_id', 'attention_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attentions_benefits')
    op.drop_table('attentions')
    op.drop_table('pets')
    op.drop_index(op.f('ix_users_rut'), table_name='users')
    op.drop_table('users')
    op.drop_table('benefits')
    # ### end Alembic commands ###
