"""StockChange.change

Revision ID: 355b714df809
Revises: c0e50f404754
Create Date: 2023-06-08 09:56:36.903030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355b714df809'
down_revision = 'c0e50f404754'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_changes', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('stock_changes', 'change')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_changes', sa.Column('change', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('stock_changes', 'quantity')
    # ### end Alembic commands ###
